project:
  type: website
website:
  title: "Tonkin Lab website"
  site-url: https://tonkinlab.org/
  page-navigation: true
  google-analytics: "G-D2HGF12X7H"
  back-to-top-navigation: true
  twitter-card:
    creator: "@jdtonkin"
  favicon: assets/img/icon-512.png
  open-graph: true
  navbar:
    #background: transparent
    search: true
    logo: /assets/img/logo-new-2.png
    title: false
    right:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: People
      - research.qmd
      - publications.qmd
      - blog.qmd
      - opportunities.qmd
      # - icon: rss
      #   href: index.xml
  page-footer:
    left:  Made with {{< iconify fa-brands r-project >}} and [quarto](https://quarto.org)
    right:
      - icon: github
        href: https://github.com/tonkinlab
      - 2024 {{< iconify fa copyright >}} J. D. Tonkin.
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
#    page-layout: full
execute:
  freeze: auto
editor:
  mode: source

